"""
Alert Router

This module provides API endpoints for the Alert System.

Endpoints:
- GET /api/v1/alert/ - List alerts with filtering
- GET /api/v1/alert/{id} - Get specific alert
- PUT /api/v1/alert/{id} - Update alert (mark as read/acknowledged)
- DELETE /api/v1/alert/{id} - Delete alert
- PUT /api/v1/alert/bulk - Bulk update alerts
- DELETE /api/v1/alert/bulk - Bulk delete alerts
- GET /api/v1/alert/stats/summary - Get alert statistics
- POST /api/v1/alert/check - Manually trigger alert checks

Learning Notes:
- Alerts are automatically generated by the alert service
- Users can mark alerts as read or acknowledged
- Bulk operations allow managing multiple alerts at once
- Statistics provide overview of alert status
- Manual check endpoint allows on-demand alert generation
"""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from sqlalchemy import desc, func
from typing import List
from datetime import datetime, timedelta

from database import get_db
from dependencies.auth import get_current_user
from models.user import User
from models.alert import Alert
from schemas.alert import (
    AlertResponse,
    AlertUpdate,
    AlertFilter,
    AlertStatistics,
    BulkAlertUpdate,
    AlertType,
    AlertSeverity
)
from services.alert_service import AlertService

router = APIRouter(prefix="/alert", tags=["alerts"])


@router.get("/", response_model=List[AlertResponse])
def list_alerts(
    filter_params: AlertFilter = Depends(),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    List alerts with filtering
    
    Filters:
    - type: Filter by alert type (weather, pest, sensor, system)
    - severity: Filter by severity (info, warning, critical)
    - is_read: Filter by read status
    - is_acknowledged: Filter by acknowledged status
    - skip: Number of records to skip (pagination)
    - limit: Maximum number of records to return
    
    Returns:
        List of alerts
    """
    query = db.query(Alert).filter(Alert.user_id == current_user.id)
    
    # Apply filters
    if filter_params.type:
        query = query.filter(Alert.type == filter_params.type.value)
    
    if filter_params.severity:
        query = query.filter(Alert.severity == filter_params.severity.value)
    
    if filter_params.is_read is not None:
        query = query.filter(Alert.is_read == filter_params.is_read)
    
    if filter_params.is_acknowledged is not None:
        query = query.filter(Alert.is_acknowledged == filter_params.is_acknowledged)
    
    # Order by created_at descending (newest first)
    query = query.order_by(desc(Alert.created_at))
    
    # Apply pagination
    alerts = query.offset(filter_params.skip).limit(filter_params.limit).all()
    
    return alerts


@router.get("/{alert_id}", response_model=AlertResponse)
def get_alert(
    alert_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Get a specific alert by ID
    
    Args:
        alert_id: Alert ID
        
    Returns:
        Alert details
        
    Raises:
        404: Alert not found
    """
    alert = db.query(Alert).filter(
        Alert.id == alert_id,
        Alert.user_id == current_user.id
    ).first()
    
    if not alert:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Alert not found"
        )
    
    return alert


@router.put("/{alert_id}", response_model=AlertResponse)
def update_alert(
    alert_id: int,
    alert_update: AlertUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Update an alert (mark as read/acknowledged)
    
    Args:
        alert_id: Alert ID
        alert_update: Update data
        
    Returns:
        Updated alert
        
    Raises:
        404: Alert not found
    """
    alert = db.query(Alert).filter(
        Alert.id == alert_id,
        Alert.user_id == current_user.id
    ).first()
    
    if not alert:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Alert not found"
        )
    
    # Update fields
    if alert_update.is_read is not None:
        alert.is_read = alert_update.is_read
    
    if alert_update.is_acknowledged is not None:
        alert.is_acknowledged = alert_update.is_acknowledged
    
    db.commit()
    db.refresh(alert)
    
    return alert


@router.delete("/{alert_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_alert(
    alert_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Delete an alert
    
    Args:
        alert_id: Alert ID
        
    Raises:
        404: Alert not found
    """
    alert = db.query(Alert).filter(
        Alert.id == alert_id,
        Alert.user_id == current_user.id
    ).first()
    
    if not alert:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Alert not found"
        )
    
    db.delete(alert)
    db.commit()
    
    return None


@router.put("/bulk", response_model=dict)
def bulk_update_alerts(
    bulk_update: BulkAlertUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Bulk update multiple alerts
    
    Args:
        bulk_update: Bulk update data with alert IDs
        
    Returns:
        Number of alerts updated
    """
    # Get alerts
    alerts = db.query(Alert).filter(
        Alert.id.in_(bulk_update.alert_ids),
        Alert.user_id == current_user.id
    ).all()
    
    if not alerts:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No alerts found with the provided IDs"
        )
    
    # Update alerts
    updated_count = 0
    for alert in alerts:
        if bulk_update.is_read is not None:
            alert.is_read = bulk_update.is_read
        
        if bulk_update.is_acknowledged is not None:
            alert.is_acknowledged = bulk_update.is_acknowledged
        
        updated_count += 1
    
    db.commit()
    
    return {
        "message": f"Successfully updated {updated_count} alerts",
        "updated_count": updated_count
    }


@router.delete("/bulk", status_code=status.HTTP_200_OK)
def bulk_delete_alerts(
    alert_ids: List[int],
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Bulk delete multiple alerts
    
    Args:
        alert_ids: List of alert IDs to delete
        
    Returns:
        Number of alerts deleted
    """
    # Get alerts
    alerts = db.query(Alert).filter(
        Alert.id.in_(alert_ids),
        Alert.user_id == current_user.id
    ).all()
    
    if not alerts:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No alerts found with the provided IDs"
        )
    
    # Delete alerts
    deleted_count = len(alerts)
    for alert in alerts:
        db.delete(alert)
    
    db.commit()
    
    return {
        "message": f"Successfully deleted {deleted_count} alerts",
        "deleted_count": deleted_count
    }


@router.get("/stats/summary", response_model=AlertStatistics)
def get_alert_statistics(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Get alert statistics
    
    Returns:
        Alert statistics including:
        - Total alerts
        - Unread alerts
        - Unacknowledged alerts
        - Alerts by type
        - Alerts by severity
        - Recent critical alerts (last 24 hours)
    """
    # Total alerts
    total_alerts = db.query(func.count(Alert.id)).filter(
        Alert.user_id == current_user.id
    ).scalar()
    
    # Unread alerts
    unread_alerts = db.query(func.count(Alert.id)).filter(
        Alert.user_id == current_user.id,
        Alert.is_read == False
    ).scalar()
    
    # Unread alerts (no is_acknowledged field, using is_read instead)
    # Note: The Alert model doesn't have is_acknowledged, only is_read
    
    # Alerts by type
    alerts_by_type = {}
    for alert_type in AlertType:
        count = db.query(func.count(Alert.id)).filter(
            Alert.user_id == current_user.id,
            Alert.alert_type == alert_type
        ).scalar()
        alerts_by_type[alert_type.value] = count
    
    # Alerts by severity
    alerts_by_severity = {}
    for severity in AlertSeverity:
        count = db.query(func.count(Alert.id)).filter(
            Alert.user_id == current_user.id,
            Alert.severity == severity
        ).scalar()
        alerts_by_severity[severity.value] = count
    
    # Recent critical alerts (last 24 hours)
    one_day_ago = datetime.utcnow() - timedelta(days=1)
    recent_critical_alerts = db.query(func.count(Alert.id)).filter(
        Alert.user_id == current_user.id,
        Alert.severity == AlertSeverity.CRITICAL,
        Alert.created_at >= one_day_ago
    ).scalar()
    
    return AlertStatistics(
        total_alerts=total_alerts,
        unread_alerts=unread_alerts,
        unacknowledged_alerts=unread_alerts,  # Using unread_alerts since is_acknowledged doesn't exist
        alerts_by_type=alerts_by_type,
        alerts_by_severity=alerts_by_severity,
        recent_critical_alerts=recent_critical_alerts
    )


@router.post("/check", response_model=dict)
def check_alerts(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Manually trigger alert checks
    
    This endpoint runs all alert checks:
    - Sensor data thresholds
    - Pest detections
    - Weather conditions (if available)
    
    Returns:
        Number of new alerts generated
    """
    # Run alert checks
    new_alerts = AlertService.run_alert_checks(db, current_user.id)
    
    return {
        "message": f"Alert check completed. Generated {len(new_alerts)} new alerts.",
        "new_alerts_count": len(new_alerts),
        "alert_ids": [alert.id for alert in new_alerts]
    }
