"""Add weather_condition to sensor_readings

Revision ID: 5e85c651e162
Revises: a1b2c3d4e5f6
Create Date: 2026-03-05 11:07:41.235026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e85c651e162'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Apply the migration (upgrade database schema).
    
    This function contains the changes to apply to the database.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_readings', sa.Column('weather_condition', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert the migration (downgrade database schema).
    
    This function contains the changes to undo the migration.
    Always write downgrade functions so you can rollback if needed!
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_readings', 'weather_condition')
    # ### end Alembic commands ###
