"""Add email column to users table

Revision ID: 3028bdbbd5c9
Revises: 5e85c651e162
Create Date: 2026-03-14 18:25:07.195658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3028bdbbd5c9'
down_revision = '5e85c651e162'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Apply the migration (upgrade database schema).
    
    This function contains the changes to apply to the database.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True, comment='User email address (required for new signups, optional for existing users)'))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert the migration (downgrade database schema).
    
    This function contains the changes to undo the migration.
    Always write downgrade functions so you can rollback if needed!
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
