"""
PestDetection Model

Stores pest detection results from ML-based image analysis.
This is a CORE FEATURE for the Pest Risk Management System.

Educational Notes:
- This model stores results from the ML pest detection service
- Each record represents one image upload and its detection results
- Supports multiple pest types per image (stored as JSON array)
- Confidence scores help users understand detection reliability
"""

from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey, Text, JSON, Enum as SQLEnum
from sqlalchemy.orm import relationship
from datetime import datetime
import enum

from database import Base


class SeverityLevel(enum.Enum):
    """
    Pest infestation severity levels
    
    Educational Note:
    - Using Python Enum ensures only valid values are stored
    - Helps with data validation and API responses
    - Makes code more maintainable (no magic strings)
    """
    LOW = "low"           # Minor pest presence, monitor only
    MEDIUM = "medium"     # Moderate infestation, consider treatment
    HIGH = "high"         # Severe infestation, immediate action needed
    CRITICAL = "critical" # Crop-threatening, urgent intervention required


class PestDetection(Base):
    """
    PestDetection model for storing pest detection results
    
    Table: pest_detections
    
    Educational Notes:
    - This is the core table for the Pest Risk Management System
    - Stores both the image and the ML detection results
    - Links to User so each farmer sees only their detections
    - JSON field stores complex detection data (multiple pests, bounding boxes)
    
    Workflow:
    1. User uploads image via mobile app
    2. Backend saves image to /uploads folder
    3. ML service analyzes image
    4. Results stored in this table
    5. User sees results in app history
    """
    
    __tablename__ = "pest_detections"
    
    # Primary Key
    id = Column(Integer, primary_key=True, index=True)
    
    # Foreign Key to User
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    
    # Image Information
    image_url = Column(String(500), nullable=False)
    """
    Path to uploaded image (e.g., "/uploads/pest_images/abc123.jpg")
    
    Educational Note:
    - We store the file path, not the actual image binary
    - Storing files in database is slow and inefficient
    - File system is better for large binary data
    """
    
    # Detection Results
    pest_type = Column(String(100), nullable=True)
    """
    Primary pest detected (e.g., "Aphids", "Whiteflies", "Leaf Miner")
    
    Educational Note:
    - Nullable because ML might not detect any pest
    - If multiple pests detected, this is the most confident one
    - Full detection data stored in detections_json
    """
    
    confidence_score = Column(Float, nullable=True)
    """
    ML model confidence (0.0 to 1.0)
    
    Educational Note:
    - 0.0 = 0% confident (no pest detected)
    - 1.0 = 100% confident (definitely this pest)
    - Typically we only show results with confidence > 0.5
    - Helps users understand reliability of detection
    """
    
    severity_level = Column(SQLEnum(SeverityLevel), nullable=True)
    """
    Infestation severity level
    
    Educational Note:
    - Determined by ML model or business logic
    - Helps farmers prioritize which fields need attention
    - Used for alert generation (HIGH/CRITICAL trigger alerts)
    """
    
    detections_json = Column(JSON, nullable=True)
    """
    Full detection results as JSON
    
    Example:
    {
        "detections": [
            {
                "pest_type": "Aphids",
                "confidence": 0.92,
                "bounding_box": {"x": 100, "y": 150, "width": 50, "height": 60}
            },
            {
                "pest_type": "Whiteflies",
                "confidence": 0.78,
                "bounding_box": {"x": 200, "y": 250, "width": 40, "height": 50}
            }
        ],
        "total_pests": 2,
        "processing_time_ms": 1234
    }
    
    Educational Note:
    - JSON column stores complex nested data
    - Flexible schema (can add new fields without migration)
    - Good for ML results that vary by model version
    """
    
    recommendations = Column(Text, nullable=True)
    """
    Treatment recommendations for detected pest
    
    Educational Note:
    - Text field for long-form content
    - Could be generated by ML model or looked up from database
    - Helps farmers take action (not just identify pest)
    """
    
    # Timestamps
    detected_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    """
    When the detection was performed
    
    Educational Note:
    - Automatically set when record is created
    - Used for sorting history (newest first)
    - Used for analytics (pest trends over time)
    """
    
    # Relationships
    user = relationship("User", back_populates="pest_detections")
    """
    Link back to the User who uploaded this image
    
    Educational Note:
    - Allows querying: user.pest_detections (all detections for a user)
    - Cascade delete: if user deleted, their detections are deleted too
    """
    
    # Indexes for Performance
    __table_args__ = (
        # Composite index for user's detection history queries
        # Query: "Get all detections for user X, ordered by date"
        {"comment": "Pest detection records from ML-based image analysis"},
    )
    
    def __repr__(self):
        """String representation for debugging"""
        return f"<PestDetection(id={self.id}, user_id={self.user_id}, pest_type={self.pest_type}, confidence={self.confidence_score})>"
    
    def to_dict(self):
        """
        Convert model to dictionary for API responses
        
        Educational Note:
        - FastAPI can't directly serialize SQLAlchemy models
        - We convert to dict, then FastAPI converts to JSON
        - Excludes user object to avoid circular references
        """
        return {
            "id": self.id,
            "user_id": self.user_id,
            "image_url": self.image_url,
            "pest_type": self.pest_type,
            "confidence_score": self.confidence_score,
            "severity_level": self.severity_level.value if self.severity_level else None,
            "detections_json": self.detections_json,
            "recommendations": self.recommendations,
            "detected_at": self.detected_at.isoformat() if self.detected_at else None,
        }
    
    def is_high_risk(self):
        """
        Check if this detection indicates high pest risk
        
        Educational Note:
        - Business logic method
        - Used for alert generation
        - HIGH or CRITICAL severity triggers alerts
        """
        return self.severity_level in [SeverityLevel.HIGH, SeverityLevel.CRITICAL]
    
    def get_alert_message(self):
        """
        Generate alert message for high-risk detections
        
        Educational Note:
        - Helper method for alert system
        - Returns user-friendly message
        - Used in push notifications and in-app alerts
        """
        if not self.is_high_risk():
            return None
        
        severity_text = "CRITICAL" if self.severity_level == SeverityLevel.CRITICAL else "HIGH"
        return f"{severity_text} PEST ALERT: {self.pest_type} detected with {self.confidence_score*100:.0f}% confidence. {self.recommendations or 'Take immediate action.'}"


# Educational Notes:
# 
# 1. Why store image_url instead of image binary?
#    - File system is faster for large files
#    - Database backups are smaller
#    - Easier to serve images via CDN/static hosting
#    - Can delete old images without database migration
#
# 2. Why use JSON for detections_json?
#    - ML models return complex nested data
#    - Schema can evolve without database migrations
#    - Can store multiple detections per image
#    - Flexible for different ML model versions
#
# 3. Why have both pest_type and detections_json?
#    - pest_type = quick access to primary detection
#    - detections_json = full details for advanced users
#    - Allows simple queries: "Show all Aphid detections"
#    - Avoids parsing JSON for common operations
#
# 4. Severity levels and alerts:
#    - LOW/MEDIUM = informational, no alert
#    - HIGH = warning alert, consider action
#    - CRITICAL = urgent alert, immediate action
#    - Helps farmers prioritize limited resources
#
# 5. Integration with Pest Risk Management System:
#    - This model stores REACTIVE detections (user uploads image)
#    - Combined with SensorReading data for PROACTIVE predictions
#    - Example: High humidity + past Aphid detections = High risk alert
