"""
SensorReading Model

This model stores simulated IoT sensor data for environmental monitoring.
Part of the Weather Early Warning System (CORE FEATURE #1).

Educational Notes:
- This represents data from virtual sensors (no physical hardware)
- Data is generated by a Python script (synthetic/simulated)
- In a real system, this would come from ESP32/Arduino devices
- Stores time-series data (readings over time)
"""

from sqlalchemy import Column, Integer, Float, DateTime, ForeignKey, Index
from sqlalchemy.orm import relationship
from datetime import datetime, timezone
from database import Base


class SensorReading(Base):
    """
    Stores environmental sensor readings for weather monitoring.
    
    This is the foundation of the Weather Early Warning System.
    Readings are used to:
    1. Display current conditions on dashboard
    2. Detect weather anomalies (extreme values)
    3. Predict pest risks (based on environmental conditions)
    4. Generate alerts when thresholds are exceeded
    
    Data Source: Synthetic data generator (Python script)
    Update Frequency: Every 30 seconds (simulated)
    """
    
    __tablename__ = "sensor_readings"
    
    # Primary Key
    id = Column(Integer, primary_key=True, index=True)
    # Auto-incrementing ID for each reading
    
    # Foreign Key to User
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    # Links reading to a specific user/farm
    # CASCADE: If user is deleted, delete all their readings
    
    # Sensor Data Fields
    temperature = Column(Float, nullable=False)
    # Temperature in Celsius (°C)
    # Typical range for Malaysia: 25-35°C
    # Alert threshold: >35°C (extreme heat)
    
    humidity = Column(Float, nullable=False)
    # Relative humidity as percentage (%)
    # Typical range: 60-90%
    # Alert threshold: >85% (high humidity, pest risk)
    
    soil_moisture = Column(Float, nullable=False)
    # Soil moisture as percentage (%)
    # Range: 0-100%
    # Alert threshold: <30% (dry soil, irrigation needed)
    
    light_intensity = Column(Float, nullable=False)
    # Light intensity in lux
    # Typical range: 0-100,000 lux
    # 0 = night, 50,000+ = bright sunlight
    # Used for day/night detection and crop growth monitoring
    
    # Timestamp
    timestamp = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        index=True
    )
    # When this reading was taken
    # Indexed for fast time-based queries (e.g., "last 24 hours")
    # Uses UTC timezone for consistency
    
    # Relationships
    user = relationship("User", back_populates="sensor_readings")
    # Access the user who owns this reading: reading.user.username
    # Access all readings for a user: user.sensor_readings
    
    # Database Indexes for Performance
    __table_args__ = (
        # Composite index for common query: "Get user's recent readings"
        Index('idx_user_timestamp', 'user_id', 'timestamp'),
        # Allows fast queries like: "Get last 100 readings for user X"
        
        # Index for time-based queries
        Index('idx_timestamp_desc', 'timestamp'),
        # Allows fast queries like: "Get most recent reading across all users"
    )
    
    def to_dict(self):
        """
        Convert model to dictionary for API responses.
        
        Returns:
            dict: Sensor reading data in JSON-friendly format
        """
        return {
            "id": self.id,
            "user_id": self.user_id,
            "temperature": round(self.temperature, 2),  # Round to 2 decimal places
            "humidity": round(self.humidity, 2),
            "soil_moisture": round(self.soil_moisture, 2),
            "light_intensity": round(self.light_intensity, 2),
            "timestamp": self.timestamp.isoformat(),  # Convert to ISO 8601 string
        }
    
    def is_anomaly(self):
        """
        Check if this reading contains anomalous values.
        Used for weather early warning system.
        
        Returns:
            dict: Anomaly status and reasons
        """
        anomalies = []
        
        # Check temperature (extreme heat)
        if self.temperature > 35:
            anomalies.append(f"Extreme heat: {self.temperature}°C")
        elif self.temperature < 20:
            anomalies.append(f"Unusually cold: {self.temperature}°C")
        
        # Check humidity (pest risk)
        if self.humidity > 85:
            anomalies.append(f"High humidity: {self.humidity}% (pest risk)")
        elif self.humidity < 40:
            anomalies.append(f"Low humidity: {self.humidity}%")
        
        # Check soil moisture (irrigation needed)
        if self.soil_moisture < 30:
            anomalies.append(f"Dry soil: {self.soil_moisture}% (irrigation needed)")
        elif self.soil_moisture > 80:
            anomalies.append(f"Waterlogged soil: {self.soil_moisture}%")
        
        return {
            "is_anomaly": len(anomalies) > 0,
            "anomalies": anomalies
        }
    
    def __repr__(self):
        """String representation for debugging"""
        return (
            f"<SensorReading(id={self.id}, user_id={self.user_id}, "
            f"temp={self.temperature}°C, humidity={self.humidity}%, "
            f"timestamp={self.timestamp})>"
        )


# ============================================================================
# LEARNING NOTES
# ============================================================================

"""
1. TIME-SERIES DATA:
   - Sensor readings are time-series data (values over time)
   - Each reading is a snapshot at a specific moment
   - Queries often involve time ranges: "last 24 hours", "last week"
   - Indexes on timestamp are crucial for performance

2. SIMULATED DATA:
   - This project uses synthetic data (no real sensors)
   - A Python script generates realistic values
   - Simulates sensor behavior: gradual changes, occasional spikes
   - Allows testing without hardware

3. ALERT THRESHOLDS:
   - is_anomaly() method checks if values are concerning
   - Thresholds based on Malaysian climate and crop needs
   - Used by Alert System to notify farmers
   - Can be customized per crop type in future

4. DATABASE PERFORMANCE:
   - Composite index (user_id, timestamp) speeds up common queries
   - Without index: Database scans all rows (slow)
   - With index: Database jumps directly to relevant rows (fast)
   - Critical for apps with lots of sensor data

5. RELATIONSHIP TO OTHER FEATURES:
   - Dashboard: Displays latest reading (SELECT * ORDER BY timestamp DESC LIMIT 1)
   - Weather Alerts: Checks is_anomaly() every 30 seconds
   - Pest Prediction: Uses temp + humidity to predict pest risk
   - Historical Charts: Queries readings over time range

6. REAL-WORLD CONSIDERATIONS:
   - Production systems might store millions of readings
   - Consider data retention policy (delete old data after 90 days)
   - Consider aggregation (store hourly averages instead of every reading)
   - Consider time-series databases (InfluxDB, TimescaleDB) for scale
"""
