"""
Alert Schemas

This module defines Pydantic schemas for the Alert System.
Alerts are automatically generated based on:
- Sensor data thresholds (temperature, humidity, soil moisture)
- Weather conditions (heavy rain, strong wind, extreme temperature)
- Pest detections (high confidence detections)

Learning Notes:
- Alerts have severity levels: info, warning, critical
- Alerts have types: weather, pest, sensor, system
- Alerts can be marked as read/acknowledged
- Alerts are automatically generated by background tasks
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Annotated
from datetime import datetime
from enum import Enum


class AlertType(str, Enum):
    """Alert type enumeration (PRD v2)"""
    # Weather alerts
    WEATHER = "weather"
    HEAVY_RAIN = "heavy_rain"
    EXTREME_HEAT = "extreme_heat"
    STORM_WARNING = "storm_warning"
    LOW_TEMPERATURE = "low_temperature"

    # Pest alerts (PRD v2 differentiation)
    PEST = "pest"                          # Legacy
    PEST_DETECTION = "pest_detection"      # From image upload (detected)
    PEST_RISK_WARNING = "pest_risk_warning"  # From weather-pest correlation (predicted)
    PEST_RISK = "pest_risk"                # Legacy

    # Environmental
    SENSOR = "sensor"
    LOW_SOIL_MOISTURE = "low_soil_moisture"
    HIGH_HUMIDITY = "high_humidity"

    # System
    SYSTEM = "system"


class AlertSeverity(str, Enum):
    """Alert severity enumeration"""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertCreate(BaseModel):
    """Schema for creating a new alert"""
    type: AlertType = Field(..., description="Type of alert")
    severity: AlertSeverity = Field(..., description="Severity level")
    title: str = Field(..., min_length=1, max_length=200, description="Alert title")
    message: str = Field(..., min_length=1, max_length=1000, description="Alert message")
    source_id: Optional[int] = Field(None, description="ID of the source entity (sensor_id, pest_detection_id, etc.)")
    source_type: Optional[str] = Field(None, description="Type of source entity")
    metadata: Optional[dict] = Field(default_factory=dict, description="Additional metadata")

    class Config:
        json_schema_extra = {
            "example": {
                "type": "sensor",
                "severity": "warning",
                "title": "High Temperature Alert",
                "message": "Temperature has exceeded 32°C. Consider irrigation.",
                "source_id": 123,
                "source_type": "sensor_data",
                "metadata": {
                    "temperature": 33.5,
                    "threshold": 32.0
                }
            }
        }


class AlertUpdate(BaseModel):
    """Schema for updating an alert"""
    is_read: Optional[bool] = Field(default=None, description="Mark as read")
    is_acknowledged: Optional[bool] = Field(default=None, description="Mark as acknowledged")

    class Config:
        json_schema_extra = {
            "example": {
                "is_read": True,
                "is_acknowledged": True
            }
        }


class AlertResponse(BaseModel):
    """Schema for alert response (PRD v2)"""
    id: int
    user_id: int
    alert_type: str  # Changed from 'type' to 'alert_type' to match model
    severity: str  # Changed to str to accept model enum values
    title: str
    message: str
    recommendations: Optional[str] = None  # PRD v2: Include recommendations in response
    source_id: Optional[int] = None
    source_type: Optional[str] = None
    alert_metadata: Optional[dict] = None  # Changed from 'metadata' to 'alert_metadata'
    is_read: bool
    is_acknowledged: bool = False
    created_at: datetime
    expires_at: Optional[datetime] = None  # PRD v2: Include expiration time

    class Config:
        from_attributes = True
        json_schema_extra = {
            "example": {
                "id": 1,
                "user_id": 1,
                "alert_type": "pest_risk_warning",
                "severity": "high",
                "title": "Pest Risk Warning: Rice Stem Borer",
                "message": "Weather conditions indicate elevated risk of Rice Stem Borer.",
                "recommendations": "• Monitor rice stems for entry holes\n• Apply biological control\n• Remove infected stems",
                "source_id": None,
                "source_type": None,
                "alert_metadata": {
                    "pest_name": "Rice Stem Borer",
                    "risk_level": "high",
                    "weather_conditions": {"temp": 28, "humidity": 85},
                    "source": "weather_pest_correlation"
                },
                "is_read": False,
                "is_acknowledged": False,
                "created_at": "2025-01-04T10:30:00",
                "expires_at": None
            }
        }


class AlertFilter(BaseModel):
    """Schema for filtering alerts"""
    type: Optional[str] = Field(default=None, description="Filter by alert type (accepts model enum values)")
    severity: Optional[str] = Field(default=None, description="Filter by severity (accepts model enum values)")
    is_read: Optional[bool] = Field(default=None, description="Filter by read status")
    is_acknowledged: Optional[bool] = Field(default=None, description="Filter by acknowledged status")
    skip: int = Field(default=0, ge=0, description="Number of records to skip")
    limit: int = Field(default=100, ge=1, le=100, description="Maximum number of records to return")

    class Config:
        json_schema_extra = {
            "example": {
                "type": "sensor",
                "severity": "warning",
                "is_read": False,
                "skip": 0,
                "limit": 20
            }
        }


class AlertStatistics(BaseModel):
    """Schema for alert statistics"""
    total_alerts: int
    unread_alerts: int
    unacknowledged_alerts: int
    alerts_by_type: dict
    alerts_by_severity: dict
    recent_critical_alerts: int

    class Config:
        json_schema_extra = {
            "example": {
                "total_alerts": 150,
                "unread_alerts": 12,
                "unacknowledged_alerts": 8,
                "alerts_by_type": {
                    "weather": 45,
                    "pest": 30,
                    "sensor": 60,
                    "system": 15
                },
                "alerts_by_severity": {
                    "info": 80,
                    "warning": 50,
                    "critical": 20
                },
                "recent_critical_alerts": 3
            }
        }


class BulkAlertUpdate(BaseModel):
    """Schema for bulk updating alerts"""
    alert_ids: Annotated[List[int], Field(min_items=1, description="List of alert IDs to update")]
    is_read: Optional[bool] = Field(default=None, description="Mark as read")
    is_acknowledged: Optional[bool] = Field(default=None, description="Mark as acknowledged")

    class Config:
        json_schema_extra = {
            "example": {
                "alert_ids": [1, 2, 3, 4, 5],
                "is_read": True,
                "is_acknowledged": False
            }
        }
